//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.OSE.Service.OSE {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sunat.gob.pe/")]
    public partial class SOAPException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sunat.gob.pe")]
    public partial class StatusCdr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroComprobanteField;
        
        private string rucComprobanteField;
        
        private string serieComprobanteField;
        
        private string tipoComprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rucComprobante {
            get {
                return this.rucComprobanteField;
            }
            set {
                this.rucComprobanteField = value;
                this.RaisePropertyChanged("rucComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serieComprobante {
            get {
                return this.serieComprobanteField;
            }
            set {
                this.serieComprobanteField = value;
                this.RaisePropertyChanged("serieComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.sunat.gob.pe/", ConfigurationName="OSE.BizlinksOSE")]
    public interface BizlinksOSE {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://service.sunat.gob.pe) of message getStatusCdr does not match the default value (http://service.sunat.gob.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStatusCdr", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Billing.OSE.Service.OSE.SOAPException), Action="urn:getStatusCdr", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Billing.OSE.Service.OSE.getStatusCdrResponse getStatusCdr(Billing.OSE.Service.OSE.getStatusCdr request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStatusCdr", ReplyAction="*")]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusCdrResponse> getStatusCdrAsync(Billing.OSE.Service.OSE.getStatusCdr request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://service.sunat.gob.pe) of message sendPack does not match the default value (http://service.sunat.gob.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendPack", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Billing.OSE.Service.OSE.SOAPException), Action="urn:sendPack", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Billing.OSE.Service.OSE.sendPackResponse sendPack(Billing.OSE.Service.OSE.sendPack request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendPack", ReplyAction="*")]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendPackResponse> sendPackAsync(Billing.OSE.Service.OSE.sendPack request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://service.sunat.gob.pe) of message sendBill does not match the default value (http://service.sunat.gob.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendBill", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Billing.OSE.Service.OSE.SOAPException), Action="urn:sendBill", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Billing.OSE.Service.OSE.sendBillResponse sendBill(Billing.OSE.Service.OSE.sendBill request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendBill", ReplyAction="*")]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendBillResponse> sendBillAsync(Billing.OSE.Service.OSE.sendBill request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://service.sunat.gob.pe) of message getStatus does not match the default value (http://service.sunat.gob.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Billing.OSE.Service.OSE.SOAPException), Action="urn:getStatus", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Billing.OSE.Service.OSE.getStatusResponse getStatus(Billing.OSE.Service.OSE.getStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusResponse> getStatusAsync(Billing.OSE.Service.OSE.getStatus request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://service.sunat.gob.pe) of message sendSummary does not match the default value (http://service.sunat.gob.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSummary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Billing.OSE.Service.OSE.SOAPException), Action="urn:sendSummary", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Billing.OSE.Service.OSE.sendSummaryResponse sendSummary(Billing.OSE.Service.OSE.sendSummary request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSummary", ReplyAction="*")]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendSummaryResponse> sendSummaryAsync(Billing.OSE.Service.OSE.sendSummary request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusCdr", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class getStatusCdr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Billing.OSE.Service.OSE.StatusCdr statusCdr;
        
        public getStatusCdr() {
        }
        
        public getStatusCdr(Billing.OSE.Service.OSE.StatusCdr statusCdr) {
            this.statusCdr = statusCdr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusCdrResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class getStatusCdrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] document;
        
        public getStatusCdrResponse() {
        }
        
        public getStatusCdrResponse(byte[] document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPack", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendPack {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] contentFile;
        
        public sendPack() {
        }
        
        public sendPack(string fileName, byte[] contentFile) {
            this.fileName = fileName;
            this.contentFile = contentFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPackResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendPackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        public sendPackResponse() {
        }
        
        public sendPackResponse(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBill", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendBill {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] contentFile;
        
        public sendBill() {
        }
        
        public sendBill(string fileName, byte[] contentFile) {
            this.fileName = fileName;
            this.contentFile = contentFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBillResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] applicationResponse;
        
        public sendBillResponse() {
        }
        
        public sendBillResponse(byte[] applicationResponse) {
            this.applicationResponse = applicationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sunat.gob.pe")]
    public partial class statusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class getStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        public getStatus() {
        }
        
        public getStatus(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Billing.OSE.Service.OSE.statusResponse status;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(Billing.OSE.Service.OSE.statusResponse status) {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSummary", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendSummary {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] contentFile;
        
        public sendSummary() {
        }
        
        public sendSummary(string fileName, byte[] contentFile) {
            this.fileName = fileName;
            this.contentFile = contentFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSummaryResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class sendSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket;
        
        public sendSummaryResponse() {
        }
        
        public sendSummaryResponse(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizlinksOSEChannel : Billing.OSE.Service.OSE.BizlinksOSE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizlinksOSEClient : System.ServiceModel.ClientBase<Billing.OSE.Service.OSE.BizlinksOSE>, Billing.OSE.Service.OSE.BizlinksOSE {
        
        public BizlinksOSEClient() {
        }
        
        public BizlinksOSEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizlinksOSEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizlinksOSEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizlinksOSEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Billing.OSE.Service.OSE.getStatusCdrResponse Billing.OSE.Service.OSE.BizlinksOSE.getStatusCdr(Billing.OSE.Service.OSE.getStatusCdr request) {
            return base.Channel.getStatusCdr(request);
        }
        
        public byte[] getStatusCdr(Billing.OSE.Service.OSE.StatusCdr statusCdr) {
            Billing.OSE.Service.OSE.getStatusCdr inValue = new Billing.OSE.Service.OSE.getStatusCdr();
            inValue.statusCdr = statusCdr;
            Billing.OSE.Service.OSE.getStatusCdrResponse retVal = ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).getStatusCdr(inValue);
            return retVal.document;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusCdrResponse> Billing.OSE.Service.OSE.BizlinksOSE.getStatusCdrAsync(Billing.OSE.Service.OSE.getStatusCdr request) {
            return base.Channel.getStatusCdrAsync(request);
        }
        
        public System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusCdrResponse> getStatusCdrAsync(Billing.OSE.Service.OSE.StatusCdr statusCdr) {
            Billing.OSE.Service.OSE.getStatusCdr inValue = new Billing.OSE.Service.OSE.getStatusCdr();
            inValue.statusCdr = statusCdr;
            return ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).getStatusCdrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Billing.OSE.Service.OSE.sendPackResponse Billing.OSE.Service.OSE.BizlinksOSE.sendPack(Billing.OSE.Service.OSE.sendPack request) {
            return base.Channel.sendPack(request);
        }
        
        public string sendPack(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendPack inValue = new Billing.OSE.Service.OSE.sendPack();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            Billing.OSE.Service.OSE.sendPackResponse retVal = ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendPack(inValue);
            return retVal.ticket;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendPackResponse> Billing.OSE.Service.OSE.BizlinksOSE.sendPackAsync(Billing.OSE.Service.OSE.sendPack request) {
            return base.Channel.sendPackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendPackResponse> sendPackAsync(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendPack inValue = new Billing.OSE.Service.OSE.sendPack();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            return ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendPackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Billing.OSE.Service.OSE.sendBillResponse Billing.OSE.Service.OSE.BizlinksOSE.sendBill(Billing.OSE.Service.OSE.sendBill request) {
            return base.Channel.sendBill(request);
        }
        
        public byte[] sendBill(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendBill inValue = new Billing.OSE.Service.OSE.sendBill();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            Billing.OSE.Service.OSE.sendBillResponse retVal = ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendBill(inValue);
            return retVal.applicationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendBillResponse> Billing.OSE.Service.OSE.BizlinksOSE.sendBillAsync(Billing.OSE.Service.OSE.sendBill request) {
            return base.Channel.sendBillAsync(request);
        }
        
        public System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendBillResponse> sendBillAsync(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendBill inValue = new Billing.OSE.Service.OSE.sendBill();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            return ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendBillAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Billing.OSE.Service.OSE.getStatusResponse Billing.OSE.Service.OSE.BizlinksOSE.getStatus(Billing.OSE.Service.OSE.getStatus request) {
            return base.Channel.getStatus(request);
        }
        
        public Billing.OSE.Service.OSE.statusResponse getStatus(string ticket) {
            Billing.OSE.Service.OSE.getStatus inValue = new Billing.OSE.Service.OSE.getStatus();
            inValue.ticket = ticket;
            Billing.OSE.Service.OSE.getStatusResponse retVal = ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).getStatus(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusResponse> Billing.OSE.Service.OSE.BizlinksOSE.getStatusAsync(Billing.OSE.Service.OSE.getStatus request) {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Billing.OSE.Service.OSE.getStatusResponse> getStatusAsync(string ticket) {
            Billing.OSE.Service.OSE.getStatus inValue = new Billing.OSE.Service.OSE.getStatus();
            inValue.ticket = ticket;
            return ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).getStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Billing.OSE.Service.OSE.sendSummaryResponse Billing.OSE.Service.OSE.BizlinksOSE.sendSummary(Billing.OSE.Service.OSE.sendSummary request) {
            return base.Channel.sendSummary(request);
        }
        
        public string sendSummary(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendSummary inValue = new Billing.OSE.Service.OSE.sendSummary();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            Billing.OSE.Service.OSE.sendSummaryResponse retVal = ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendSummary(inValue);
            return retVal.ticket;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendSummaryResponse> Billing.OSE.Service.OSE.BizlinksOSE.sendSummaryAsync(Billing.OSE.Service.OSE.sendSummary request) {
            return base.Channel.sendSummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Billing.OSE.Service.OSE.sendSummaryResponse> sendSummaryAsync(string fileName, byte[] contentFile) {
            Billing.OSE.Service.OSE.sendSummary inValue = new Billing.OSE.Service.OSE.sendSummary();
            inValue.fileName = fileName;
            inValue.contentFile = contentFile;
            return ((Billing.OSE.Service.OSE.BizlinksOSE)(this)).sendSummaryAsync(inValue);
        }
    }
}
